---
# tasks file for zabbix-agent

- name: Disable Zabbix packages in EPEL repository
  blockinfile:
    path: /etc/yum.repos.d/epel.repo
    block: |
      [epel]
      excludepkgs=zabbix*

- name: Install Zabbix repository 6.0
  dnf:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-latest-6.0.el9.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Clean DNF cache
  dnf:
    update_cache: true

- name: Install Zabbix Agent 2
  dnf:
    name: zabbix-agent2
    state: present

- name: Delivery zabbix_agent2.conf from template folder
  ansible.builtin.template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: '0644'

- name: Restarted and enabled zabbix-agent2
  ansible.builtin.systemd_service:
    name: zabbix-agent2
    state: restarted
    enabled: true

- name: Add zabbix-server name to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: 'zabbix-lan'
    line: 10.100.10.253 zabbix-lan
    owner: root
    group: root
    mode: '0644'