---
- name: Install default Apache Web Server
  hosts: node-vm01.local
  become: true
  gather_facts: false

  tasks:
    - name: Install Apache Web Server
      dnf:
        name: httpd
        state: present

    - name: Start Apache and enable it on every boot
      service:
        name: httpd
        state: started
        enabled: true
