- name: Базовый фаервол (SSH + HTTP/HTTPS)
  hosts: servers
  become: true
  tasks:
    - name: Установить пакет для сохранения правил (Debian/Ubuntu)
      ansible.builtin.apt:
        name: iptables-persistent
        state: present
      when: ansible_os_family == "Debian"

    - name: Отключить firewalld (RHEL/CentOS)
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_os_family == "RedHat"

    - name: Установить пакет для сохранения правил (RHEL/CentOS)
      ansible.builtin.yum:
        name: iptables-services
        state: present
      when: ansible_os_family == "RedHat"
      register: iptables_pkg

    - name: Очистить default конфиг (RHEL/CentOS)
      ansible.builtin.copy:
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: '0600'
        content: |
          # managed by Ansible
          *filter
          :INPUT ACCEPT [0:0]
          :FORWARD ACCEPT [0:0]
          :OUTPUT ACCEPT [0:0]
          COMMIT
      when:
        - ansible_os_family == "RedHat"
        - iptables_pkg is changed

    - name: Включить iptables сервис (RHEL/CentOS)
      ansible.builtin.service:
        name: iptables
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    # === Базовые разрешения ===
    - name: Разрешить ESTABLISHED,RELATED
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Разрешить loopback
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Разрешить SSH
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        ctstate: NEW
        jump: ACCEPT

    - name: Разрешить HTTP и HTTPS
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "80,443"
        ctstate: NEW
        jump: ACCEPT
        match: multiport

    # === Политики по умолчанию ===
    - name: Политика INPUT DROP
      ansible.builtin.iptables:
        chain: INPUT
        policy: DROP

    - name: Политика FORWARD DROP
      ansible.builtin.iptables:
        chain: FORWARD
        policy: DROP

    - name: Политика OUTPUT ACCEPT
      ansible.builtin.iptables:
        chain: OUTPUT
        policy: ACCEPT

    # === Сохранение правил ===
    - name: Сохранить правила (Debian/Ubuntu)
      ansible.builtin.command: netfilter-persistent save
      when: ansible_os_family == "Debian"

    - name: Сообщить путь сохранения (Debian/Ubuntu)
      ansible.builtin.debug:
        msg: "Правила сохранены в /etc/iptables/rules.v4"
      when: ansible_os_family == "Debian"

    - name: Сохранить правила (RHEL/CentOS)
      ansible.builtin.command: service iptables save
      when: ansible_os_family == "RedHat"

    - name: Сообщить путь сохранения (RHEL/CentOS)
      ansible.builtin.debug:
        msg: "Правила сохранены в /etc/sysconfig/iptables"
      when: ansible_os_family == "RedHat"
